### ISSUE TITLE
ossPerks Logo and Twitter Avatar

### ISSUE THREAD

**Issue by nikmd23** [nikmd23/ossperks#13]
I've created the following temporary logo and Twitter avatar for [ossPerks.com](http://ossPerks.com):

![logo](https://f.cloud.github.com/assets/199026/716824/4944b42a-df3e-11e2-9564-6be9e9d7bfe3.png)

Very simple, I know. It demonstrates the range of my design capabilities. :wink: 

It'd be great to have something a little more original and attractive. I'm pretty much open to anything as long as it is clear, easy to read and non-offensive. 

Of course, since this is an open source project, we have no funds to pay for this work - but we'd be greatly thankful for your contribution.

Just reply to this issue with the graphic you'd suggest. If we get several logos, we'll vote for the best one.

**Comment by maartenba** [comment]
![untitled](https://f.cloud.github.com/assets/485230/1415404/fe60586c-3efe-11e3-978c-392d8b96d0ae.png)

**Comment by maartenba** [comment]
![2](https://f.cloud.github.com/assets/485230/1415405/26cac710-3eff-11e3-926c-ccad403b2c97.png)

**Comment by maartenba** [comment]
![3](https://f.cloud.github.com/assets/485230/1415407/637389a4-3eff-11e3-8020-7603904bcb57.png)

**Comment by maartenba** [comment]
![4](https://f.cloud.github.com/assets/485230/1415410/84cc51c6-3eff-11e3-9a7d-770259e5a1fe.png)

**Comment by nikmd23** [comment]
Thanks a lot @maartenba - I tweaked one of your designs to get the new logo:

![New Logo](http://ossperks.com/images/logo.png)

**Comment by maartenba** [comment]
Sweet!
