### ISSUE TITLE
Seperate Tools from Services?

### ISSUE THREAD

**Issue by nikmd23** [nikmd23/ossperks#4]
I'm thinking we should separate the tools from the services on the site.

In my mind a tool is something I have to install on my box and a service is something that I don't.

A few examples include:

```
+---------------+------------+
| *Tool*        | *Service*  |
|---------------|------------|
| ANTS Profiler | GitHub     |
| ReSharper     | Confluence |
| Fiddler       | Jira       |
| GhostDoc      | MyGet      |
| RegEx Buddy   | TeamCity   |
+---------------+------------+
```

With this separation we could have two calls to action. **Download** for tools and **Register** for services.

**Comment by avanderhoorn** [comment]
As long as the list of tools and services is roughly the same number side
by side should be fine. Only problem is when one is much longer than the
other.

**Comment by nikmd23** [comment]
Oh, sorry - no, I wasn't suggesting columns for layout.

I was just illustrating the difference between tools and services. I've updated the original post to be more clear.
